<?php

namespace AppBundle\Repository;

/**
 * SousThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
